const movies = [
  {
    id: 1,
    titre: "Inception",
    description:
      "A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea.",
    annee_de_sortie: 2010,
    genre: "Sci-Fi",
    realisateur: "Christopher Nolan",
    acteurs_principaux: [
      "Leonardo DiCaprio",
      "Joseph Gordon-Levitt",
      "Elliot Page",
    ],
    image: "https://image.tmdb.org/t/p/w500/8IB2e4r4oVhHnANbnm7O3Tj6tF8.jpg",
    trailer: "https://www.youtube.com/watch?v=YoHD9XEInc0",
    note: 5,
  },
  {
    id: 2,
    titre: "Interstellar",
    description:
      "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    annee_de_sortie: 2014,
    genre: "Adventure",
    realisateur: "Christopher Nolan",
    acteurs_principaux: [
      "Matthew McConaughey",
      "Anne Hathaway",
      "Jessica Chastain",
    ],
    image: "https://image.tmdb.org/t/p/w500/rAiYTfKGqDCRIIqoNMJ3vGJ2z6n.jpg",
    trailer: "https://www.youtube.com/watch?v=zSWdZVtXT7E",
    note: 5,
  },
  {
    id: 3,
    titre: "The Dark Knight",
    description:
      "Batman faces the Joker, a criminal mastermind who plunges Gotham into chaos.",
    annee_de_sortie: 2008,
    genre: "Action",
    realisateur: "Christopher Nolan",
    acteurs_principaux: ["Christian Bale", "Heath Ledger", "Aaron Eckhart"],
    image: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    trailer: "https://www.youtube.com/watch?v=EXeTwQWrcwY",
    note: 5,
  },
  {
    id: 4,
    titre: "John Wick",
    description:
      "An ex-hitman comes out of retirement to track down the gangsters that killed his dog.",
    annee_de_sortie: 2014,
    genre: "Action",
    realisateur: "Chad Stahelski",
    acteurs_principaux: ["Keanu Reeves", "Michael Nyqvist", "Alfie Allen"],
    image: "https://image.tmdb.org/t/p/w500/5vHssUeVe25bMrof1HyaPyWgaP.jpg",
    trailer: "https://www.youtube.com/watch?v=2AUmvWm5ZDQ",
    note: 4,
  },
  {
    id: 5,
    titre: "Avengers: Endgame",
    description:
      "The Avengers assemble once more to reverse Thanos' actions and restore balance.",
    annee_de_sortie: 2019,
    genre: "Superhero",
    realisateur: "Anthony Russo, Joe Russo",
    acteurs_principaux: [
      "Robert Downey Jr.",
      "Chris Evans",
      "Scarlett Johansson",
    ],
    image: "https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
    trailer: "https://www.youtube.com/watch?v=TcMBFSGVi1c",
    note: 5,
  },
  {
    id: 6,
    titre: "The Matrix",
    description:
      "A hacker discovers the nature of his reality and his role in the war against its controllers.",
    annee_de_sortie: 1999,
    genre: "Sci-Fi",
    realisateur: "The Wachowskis",
    acteurs_principaux: [
      "Keanu Reeves",
      "Laurence Fishburne",
      "Carrie-Anne Moss",
    ],
    image: "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    trailer: "https://www.youtube.com/watch?v=vKQi3bBA1y8",
    note: 5,
  },
  {
    id: 7,
    titre: "Gladiator",
    description:
      "A former Roman general sets out to exact vengeance against the corrupt emperor.",
    annee_de_sortie: 2000,
    genre: "Drama",
    realisateur: "Ridley Scott",
    acteurs_principaux: ["Russell Crowe", "Joaquin Phoenix", "Connie Nielsen"],
    image: "https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg",
    trailer: "https://www.youtube.com/watch?v=owK1qxDselE",
    note: 5,
  },
  {
    id: 8,
    titre: "Titanic",
    description:
      "A young couple from different social classes fall in love aboard the ill-fated ship.",
    annee_de_sortie: 1997,
    genre: "Romance",
    realisateur: "James Cameron",
    acteurs_principaux: ["Leonardo DiCaprio", "Kate Winslet"],
    image: "https://image.tmdb.org/t/p/w500/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg",
    trailer: "https://www.youtube.com/watch?v=kVrqfYjkTdQ",
    note: 5,
  },
  {
    id: 9,
    titre: "Joker",
    description:
      "A mentally troubled comedian embarks on a downward spiral into chaos.",
    annee_de_sortie: 2019,
    genre: "Crime",
    realisateur: "Todd Phillips",
    acteurs_principaux: ["Joaquin Phoenix", "Robert De Niro"],
    image: "https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
    trailer: "https://www.youtube.com/watch?v=zAGVQLHvwOY",
    note: 4,
  },
  {
    id: 10,
    titre: "The Shawshank Redemption",
    description:
      "Two imprisoned men bond over years, finding solace and eventual redemption.",
    annee_de_sortie: 1994,
    genre: "Drama",
    realisateur: "Frank Darabont",
    acteurs_principaux: ["Tim Robbins", "Morgan Freeman"],
    image: "https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
    trailer: "https://www.youtube.com/watch?v=6hB3S9bIaco",
    note: 5,
  },
];

export default movies;
